# Generated by Django 4.2.9 on 2026-03-13 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('website', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['company'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('superadmin', 'Super Admin'), ('staff', 'Staff'), ('client', 'Client')], default='client', max_length=20)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_clients', models.ManyToManyField(blank=True, related_name='staff_assigned', to='social_stats.client')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='social_stats.client')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('linkedin', 'LinkedIn'), ('google_my_business', 'Google My Business')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('records_synced', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='social_stats.client')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PostMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('linkedin', 'LinkedIn'), ('google_my_business', 'Google My Business')], max_length=30)),
                ('post_id', models.CharField(max_length=300)),
                ('post_url', models.URLField(blank=True)),
                ('post_type', models.CharField(blank=True, max_length=50)),
                ('caption', models.TextField(blank=True)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('impressions', models.BigIntegerField(default=0)),
                ('reach', models.BigIntegerField(default=0)),
                ('clicks', models.BigIntegerField(default=0)),
                ('likes', models.BigIntegerField(default=0)),
                ('comments', models.BigIntegerField(default=0)),
                ('shares', models.BigIntegerField(default=0)),
                ('saves', models.BigIntegerField(default=0)),
                ('video_views', models.BigIntegerField(default=0)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_metrics', to='social_stats.client')),
            ],
            options={
                'ordering': ['-published_at'],
                'unique_together': {('client', 'platform', 'post_id')},
            },
        ),
        migrations.CreateModel(
            name='PlatformCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('linkedin', 'LinkedIn'), ('google_my_business', 'Google My Business')], max_length=30)),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('token_type', models.CharField(blank=True, default='Bearer', max_length=50)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('scope', models.TextField(blank=True)),
                ('page_id', models.CharField(blank=True, max_length=200)),
                ('page_name', models.CharField(blank=True, max_length=200)),
                ('instagram_account_id', models.CharField(blank=True, max_length=200)),
                ('channel_id', models.CharField(blank=True, max_length=200)),
                ('channel_name', models.CharField(blank=True, max_length=200)),
                ('organization_id', models.CharField(blank=True, max_length=200)),
                ('organization_name', models.CharField(blank=True, max_length=200)),
                ('gmb_account_id', models.CharField(blank=True, max_length=200)),
                ('gmb_location_id', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='social_stats.client')),
            ],
            options={
                'ordering': ['platform'],
                'unique_together': {('client', 'platform')},
            },
        ),
        migrations.CreateModel(
            name='DailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('linkedin', 'LinkedIn'), ('google_my_business', 'Google My Business')], max_length=30)),
                ('date', models.DateField()),
                ('impressions', models.BigIntegerField(default=0)),
                ('reach', models.BigIntegerField(default=0)),
                ('clicks', models.BigIntegerField(default=0)),
                ('likes', models.BigIntegerField(default=0)),
                ('comments', models.BigIntegerField(default=0)),
                ('shares', models.BigIntegerField(default=0)),
                ('saves', models.BigIntegerField(default=0)),
                ('video_views', models.BigIntegerField(default=0)),
                ('followers', models.BigIntegerField(default=0)),
                ('profile_views', models.BigIntegerField(default=0)),
                ('sessions', models.BigIntegerField(default=0)),
                ('users', models.BigIntegerField(default=0)),
                ('page_views', models.BigIntegerField(default=0)),
                ('website_clicks', models.BigIntegerField(default=0)),
                ('direction_requests', models.BigIntegerField(default=0)),
                ('phone_calls', models.BigIntegerField(default=0)),
                ('engagement_rate', models.FloatField(default=0)),
                ('ctr', models.FloatField(default=0)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='social_stats.client')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['client', 'platform', 'date'], name='social_stat_client__ff4e8d_idx')],
                'unique_together': {('client', 'platform', 'date')},
            },
        ),
    ]
