# Generated by Django 5.1.6 on 2026-03-13 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('linkedin', 'LinkedIn'), ('google_my_business', 'Google My Business'), ('all', 'All Platforms')], max_length=30)),
                ('metric', models.CharField(choices=[('impressions', 'Impressions'), ('reach', 'Reach'), ('clicks', 'Clicks'), ('likes', 'Likes'), ('followers', 'Followers'), ('video_views', 'Video Views'), ('website_clicks', 'Website Clicks'), ('phone_calls', 'Phone Calls')], max_length=30)),
                ('target_value', models.BigIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='social_stats.client')),
            ],
            options={
                'ordering': ['-year', '-month', 'platform', 'metric'],
                'unique_together': {('client', 'platform', 'metric', 'month', 'year')},
            },
        ),
    ]
