# Generated by Django 5.1.6 on 2026-03-13 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_stats', '0002_add_clientgoal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(blank=True, max_length=30)),
                ('alert_type', models.CharField(choices=[('token_expired', 'Token Expired'), ('sync_failed', 'Sync Failed'), ('reach_drop', 'Reach Drop'), ('viral_post', 'Viral Post'), ('goal_at_risk', 'Goal At Risk'), ('follower_milestone', 'Follower Milestone')], max_length=30)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('dedup_key', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='social_stats.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
