# Generated by Django 5.1.6 on 2026-03-13 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_stats', '0007_add_onboardingstep'),
    ]

    operations = [
        migrations.CreateModel(
            name='ROISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_budget', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('instagram_budget', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('youtube_budget', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('linkedin_budget', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gmb_budget', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('agency_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('avg_sale_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=2.5, max_digits=5)),
                ('lead_to_sale_rate', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('currency_symbol', models.CharField(default='$', max_length=5)),
                ('monthly_revenue_goal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monthly_leads_goal', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roi_settings', to='social_stats.client')),
            ],
        ),
        migrations.CreateModel(
            name='ROIReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('total_investment', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('agency_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_clicks', models.BigIntegerField(default=0)),
                ('total_impressions', models.BigIntegerField(default=0)),
                ('total_reach', models.BigIntegerField(default=0)),
                ('website_clicks', models.BigIntegerField(default=0)),
                ('estimated_leads', models.IntegerField(default=0)),
                ('estimated_sales', models.IntegerField(default=0)),
                ('estimated_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('roi_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cost_per_click', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('cost_per_lead', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('cost_per_sale', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('platform_breakdown', models.JSONField(default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roi_reports', to='social_stats.client')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('client', 'month', 'year')},
            },
        ),
    ]
