# Generated by Django 5.1.6 on 2026-03-13 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_stats', '0008_add_roi_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('note', models.TextField(blank=True)),
                ('color', models.CharField(default='#2563EB', max_length=7)),
                ('is_client_visible', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_notes', to='social_stats.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_calendar_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CalendarPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('linkedin', 'LinkedIn'), ('google_my_business', 'Google My Business')], max_length=30)),
                ('post_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('reel', 'Reel'), ('story', 'Story'), ('carousel', 'Carousel'), ('text', 'Text'), ('article', 'Article'), ('short', 'Short')], default='image', max_length=20)),
                ('status', models.CharField(choices=[('published', 'Published'), ('scheduled', 'Scheduled'), ('draft', 'Draft'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('caption', models.TextField(blank=True)),
                ('hashtags', models.TextField(blank=True)),
                ('media_url', models.URLField(blank=True)),
                ('post_url', models.URLField(blank=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('impressions', models.BigIntegerField(default=0)),
                ('reach', models.BigIntegerField(default=0)),
                ('likes', models.BigIntegerField(default=0)),
                ('comments', models.BigIntegerField(default=0)),
                ('shares', models.BigIntegerField(default=0)),
                ('saves', models.BigIntegerField(default=0)),
                ('video_views', models.BigIntegerField(default=0)),
                ('engagement_rate', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(blank=True, max_length=300)),
                ('notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_posts', to='social_stats.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_calendar_posts', to=settings.AUTH_USER_MODEL)),
                ('post_metric', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_post', to='social_stats.postmetric')),
            ],
            options={
                'ordering': ['-scheduled_at', '-published_at'],
            },
        ),
        migrations.CreateModel(
            name='PostingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('linkedin', 'LinkedIn'), ('google_my_business', 'Google My Business')], max_length=30)),
                ('day_of_week', models.IntegerField()),
                ('hour', models.IntegerField()),
                ('minute', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=100)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posting_schedules', to='social_stats.client')),
            ],
            options={
                'ordering': ['platform', 'day_of_week', 'hour'],
                'unique_together': {('client', 'platform', 'day_of_week', 'hour', 'minute')},
            },
        ),
    ]
