# Generated by Django 5.1.6 on 2026-03-14 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_stats', '0009_add_calendar_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('category', models.CharField(choices=[('pages', 'Pages'), ('sections', 'Sections'), ('actions', 'Actions'), ('data', 'Data')], default='pages', max_length=20)),
                ('page', models.CharField(blank=True, max_length=50)),
                ('is_default_staff', models.BooleanField(default=False)),
                ('is_default_client', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ClientPageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portal_title', models.CharField(default='My Dashboard', max_length=200)),
                ('show_platform_tabs', models.BooleanField(default=True)),
                ('show_date_picker', models.BooleanField(default=True)),
                ('show_export_button', models.BooleanField(default=True)),
                ('show_sync_button', models.BooleanField(default=False)),
                ('show_posts_section', models.BooleanField(default=True)),
                ('show_reviews_section', models.BooleanField(default=False)),
                ('show_roi_section', models.BooleanField(default=False)),
                ('show_calendar', models.BooleanField(default=False)),
                ('default_platform', models.CharField(default='all', max_length=30)),
                ('default_date_range', models.IntegerField(default=30)),
                ('custom_logo_url', models.URLField(blank=True)),
                ('custom_accent_color', models.CharField(default='#2563EB', max_length=7)),
                ('welcome_message', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='page_config', to='social_stats.client')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_portal_configs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('staff', 'Staff'), ('client', 'Client')], max_length=20)),
                ('is_granted', models.BooleanField(default=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='social_stats.permission')),
            ],
            options={
                'unique_together': {('role', 'permission')},
            },
        ),
        migrations.CreateModel(
            name='StaffClientAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_sync', models.BooleanField(default=True)),
                ('can_export', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='made_assignments', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='social_stats.client')),
                ('staff_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_assignments', to='social_stats.userprofile')),
            ],
            options={
                'unique_together': {('staff_profile', 'client')},
            },
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_granted', models.BooleanField()),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_overrides', to='social_stats.permission')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_overrides', to='social_stats.userprofile')),
            ],
            options={
                'unique_together': {('user_profile', 'permission')},
            },
        ),
    ]
