# Generated by Django 5.1.6 on 2026-03-14 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_stats', '0010_add_access_management'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.TextField()),
                ('tone', models.CharField(choices=[('professional', 'Professional'), ('casual', 'Casual'), ('funny', 'Funny'), ('inspirational', 'Inspirational'), ('urgent', 'Urgent'), ('friendly', 'Friendly')], default='professional', max_length=20)),
                ('post_type', models.CharField(choices=[('promotion', 'Promotion'), ('announcement', 'Announcement'), ('educational', 'Educational'), ('behind_scenes', 'Behind the Scenes'), ('product', 'Product Showcase'), ('event', 'Event'), ('tip', 'Tip & Advice')], default='promotion', max_length=20)),
                ('platforms', models.JSONField(default=list)),
                ('keywords', models.TextField(blank=True, default='')),
                ('call_to_action', models.CharField(blank=True, default='', max_length=200)),
                ('generated_captions', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caption_requests', to='social_stats.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
