# Generated by Django 5.1.6 on 2026-03-14 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_stats', '0011_add_caption_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostIdeaSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('business_type', models.CharField(choices=[('restaurant', 'Restaurant'), ('retail', 'Retail'), ('healthcare', 'Healthcare'), ('fitness', 'Fitness'), ('real_estate', 'Real Estate'), ('education', 'Education'), ('tech', 'Tech'), ('beauty', 'Beauty'), ('legal', 'Legal'), ('finance', 'Finance'), ('other', 'Other')], max_length=50)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('upcoming_events', models.TextField(blank=True)),
                ('target_audience', models.CharField(blank=True, max_length=300)),
                ('platforms', models.JSONField(default=list)),
                ('ideas', models.JSONField(default=dict)),
                ('posts_per_week', models.IntegerField(default=5)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_idea_sets', to='social_stats.client')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_idea_sets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='PostIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField()),
                ('day_of_week', models.CharField(max_length=20)),
                ('platform', models.CharField(max_length=30)),
                ('post_type', models.CharField(max_length=30)),
                ('topic', models.CharField(max_length=500)),
                ('caption_hint', models.TextField()),
                ('hashtag_hints', models.JSONField(default=list)),
                ('best_time', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_added_to_calendar', models.BooleanField(default=False)),
                ('converted_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_idea_source', to='social_stats.calendarpost')),
                ('idea_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_ideas', to='social_stats.postideaset')),
            ],
            options={
                'ordering': ['week_number', 'id'],
            },
        ),
    ]
