# Generated by Django 4.2.9 on 2026-04-03 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_stats', '0016_add_scheduled_date_to_postidea'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postidea',
            options={'ordering': ['scheduled_date', 'week_number', 'id']},
        ),
        migrations.AddField(
            model_name='dailymetric',
            name='business_conversations',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailymetric',
            name='maps_impressions',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailymetric',
            name='photo_views',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailymetric',
            name='search_impressions',
            field=models.BigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='GMBBusinessInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, max_length=300)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True)),
                ('category', models.CharField(blank=True, max_length=200)),
                ('additional_categories', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True)),
                ('opening_date', models.DateField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_open', models.BooleanField(default=True)),
                ('regular_hours', models.JSONField(blank=True, default=dict)),
                ('special_hours', models.JSONField(blank=True, default=list)),
                ('profile_photo_url', models.URLField(blank=True)),
                ('cover_photo_url', models.URLField(blank=True)),
                ('maps_url', models.URLField(blank=True)),
                ('place_id', models.CharField(blank=True, max_length=200)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('avg_rating', models.FloatField(default=0)),
                ('total_reviews', models.IntegerField(default=0)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gmb_info', to='social_stats.client')),
            ],
        ),
        migrations.CreateModel(
            name='GMBReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_id', models.CharField(max_length=300, unique=True)),
                ('reviewer_name', models.CharField(blank=True, max_length=200)),
                ('reviewer_photo', models.URLField(blank=True)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('comment', models.TextField(blank=True)),
                ('owner_reply', models.TextField(blank=True)),
                ('reply_updated_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gmb_reviews', to='social_stats.client')),
            ],
            options={
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['client', 'published_at'], name='social_stat_client__a7d72d_idx')],
            },
        ),
    ]
