from django.db import migrations


def create_lookup_collection(apps, key, title, items):
    LookupCollection = apps.get_model('social_stats', 'LookupCollection')
    LookupItem = apps.get_model('social_stats', 'LookupItem')
    collection, _ = LookupCollection.objects.get_or_create(key=key, defaults={'title': title, 'is_public': True})
    for item in items:
        LookupItem.objects.update_or_create(
            collection=collection,
            key=item['key'],
            defaults={
                'label': item['label'],
                'value': item.get('value', item['label']),
                'parent_key': item.get('parent_key', ''),
                'sort_order': item.get('sort_order', 0),
                'is_active': item.get('is_active', True),
                'metadata': item.get('metadata', {}),
            }
        )


def forward_func(apps, schema_editor):
    create_lookup_collection(apps, 'platforms', 'Social Platforms', [
        {'key': 'facebook', 'label': 'Facebook', 'sort_order': 10},
        {'key': 'instagram', 'label': 'Instagram', 'sort_order': 20},
        {'key': 'linkedin', 'label': 'LinkedIn', 'sort_order': 30},
        {'key': 'youtube', 'label': 'YouTube', 'sort_order': 40},
        {'key': 'google_my_business', 'label': 'Google My Business', 'sort_order': 50},
    ])

    create_lookup_collection(apps, 'business_types', 'Business Types', [
        {'key': 'retail', 'label': 'Retail'},
        {'key': 'restaurant', 'label': 'Restaurant'},
        {'key': 'healthcare', 'label': 'Healthcare'},
        {'key': 'fitness', 'label': 'Fitness'},
        {'key': 'real_estate', 'label': 'Real Estate'},
        {'key': 'education', 'label': 'Education'},
        {'key': 'technology', 'label': 'Technology'},
        {'key': 'beauty', 'label': 'Beauty'},
        {'key': 'legal', 'label': 'Legal'},
        {'key': 'finance', 'label': 'Finance'},
        {'key': 'services', 'label': 'Services'},
        {'key': 'manufacturing', 'label': 'Manufacturing'},
        {'key': 'hospitality', 'label': 'Hospitality'},
        {'key': 'entertainment', 'label': 'Entertainment'},
        {'key': 'other', 'label': 'Other'},
    ])

    create_lookup_collection(apps, 'business_categories', 'Business Categories', [
        {'key': 'electronics', 'label': 'Electronics'},
        {'key': 'retail', 'label': 'Retail'},
        {'key': 'services', 'label': 'Services'},
        {'key': 'food_and_beverage', 'label': 'Food & Beverage'},
        {'key': 'healthcare', 'label': 'Healthcare'},
        {'key': 'education', 'label': 'Education'},
        {'key': 'real_estate', 'label': 'Real Estate'},
        {'key': 'automotive', 'label': 'Automotive'},
        {'key': 'hospitality', 'label': 'Hospitality'},
        {'key': 'manufacturing', 'label': 'Manufacturing'},
        {'key': 'technology', 'label': 'Technology'},
        {'key': 'fashion', 'label': 'Fashion'},
        {'key': 'sports_and_recreation', 'label': 'Sports & Recreation'},
        {'key': 'beauty_and_wellness', 'label': 'Beauty & Wellness'},
        {'key': 'home_and_garden', 'label': 'Home & Garden'},
        {'key': 'professional_services', 'label': 'Professional Services'},
        {'key': 'entertainment', 'label': 'Entertainment'},
        {'key': 'transportation', 'label': 'Transportation'},
        {'key': 'agriculture', 'label': 'Agriculture'},
        {'key': 'financial_services', 'label': 'Financial Services'},
        {'key': 'legal_services', 'label': 'Legal Services'},
        {'key': 'construction', 'label': 'Construction'},
        {'key': 'media_and_communications', 'label': 'Media & Communications'},
        {'key': 'non_profit', 'label': 'Non-Profit'},
        {'key': 'government', 'label': 'Government'},
        {'key': 'other', 'label': 'Other'},
    ])

    create_lookup_collection(apps, 'business_subcategories', 'Business Subcategories', [
        {'key': 'consumer_electronics', 'label': 'Consumer Electronics', 'parent_key': 'electronics', 'sort_order': 10},
        {'key': 'computer_stores', 'label': 'Computer Stores', 'parent_key': 'electronics', 'sort_order': 20},
        {'key': 'mobile_phones', 'label': 'Mobile Phones', 'parent_key': 'electronics', 'sort_order': 30},
        {'key': 'audio_equipment', 'label': 'Audio Equipment', 'parent_key': 'electronics', 'sort_order': 40},
        {'key': 'video_games', 'label': 'Video Games', 'parent_key': 'electronics', 'sort_order': 50},
        {'key': 'cameras', 'label': 'Cameras', 'parent_key': 'electronics', 'sort_order': 60},
        {'key': 'drones', 'label': 'Drones', 'parent_key': 'electronics', 'sort_order': 70},
        {'key': 'smart_devices', 'label': 'Smart Devices', 'parent_key': 'electronics', 'sort_order': 80},
        {'key': 'electronic_repair', 'label': 'Electronic Repair', 'parent_key': 'electronics', 'sort_order': 90},
        {'key': 'security_systems', 'label': 'Security Systems', 'parent_key': 'electronics', 'sort_order': 100},
        {'key': 'department_stores', 'label': 'Department Stores', 'parent_key': 'retail', 'sort_order': 110},
        {'key': 'specialty_shops', 'label': 'Specialty Shops', 'parent_key': 'retail', 'sort_order': 120},
        {'key': 'online_retail', 'label': 'Online Retail', 'parent_key': 'retail', 'sort_order': 130},
        {'key': 'wholesale', 'label': 'Wholesale', 'parent_key': 'retail', 'sort_order': 140},
        {'key': 'discount_stores', 'label': 'Discount Stores', 'parent_key': 'retail', 'sort_order': 150},
        {'key': 'convenience_stores', 'label': 'Convenience Stores', 'parent_key': 'retail', 'sort_order': 160},
        {'key': 'pharmacies', 'label': 'Pharmacies', 'parent_key': 'retail', 'sort_order': 170},
        {'key': 'bookstores', 'label': 'Bookstores', 'parent_key': 'retail', 'sort_order': 180},
        {'key': 'pet_stores', 'label': 'Pet Stores', 'parent_key': 'retail', 'sort_order': 190},
        {'key': 'sporting_goods', 'label': 'Sporting Goods', 'parent_key': 'retail', 'sort_order': 200},
        {'key': 'cleaning_services', 'label': 'Cleaning Services', 'parent_key': 'services', 'sort_order': 210},
        {'key': 'maintenance', 'label': 'Maintenance', 'parent_key': 'services', 'sort_order': 220},
        {'key': 'repair_services', 'label': 'Repair Services', 'parent_key': 'services', 'sort_order': 230},
        {'key': 'installation', 'label': 'Installation', 'parent_key': 'services', 'sort_order': 240},
        {'key': 'delivery', 'label': 'Delivery', 'parent_key': 'services', 'sort_order': 250},
        {'key': 'courier', 'label': 'Courier', 'parent_key': 'services', 'sort_order': 260},
        {'key': 'security_services', 'label': 'Security Services', 'parent_key': 'services', 'sort_order': 270},
        {'key': 'waste_management', 'label': 'Waste Management', 'parent_key': 'services', 'sort_order': 280},
        {'key': 'recycling', 'label': 'Recycling', 'parent_key': 'services', 'sort_order': 290},
        {'key': 'laundry', 'label': 'Laundry', 'parent_key': 'services', 'sort_order': 300},
        {'key': 'restaurants', 'label': 'Restaurants', 'parent_key': 'food_and_beverage', 'sort_order': 310},
        {'key': 'cafes', 'label': 'Cafes', 'parent_key': 'food_and_beverage', 'sort_order': 320},
        {'key': 'fast_food', 'label': 'Fast Food', 'parent_key': 'food_and_beverage', 'sort_order': 330},
        {'key': 'bakeries', 'label': 'Bakeries', 'parent_key': 'food_and_beverage', 'sort_order': 340},
        {'key': 'catering', 'label': 'Catering', 'parent_key': 'food_and_beverage', 'sort_order': 350},
        {'key': 'delivery_food', 'label': 'Delivery', 'parent_key': 'food_and_beverage', 'sort_order': 360},
        {'key': 'bars_nightclubs', 'label': 'Bars & Nightclubs', 'parent_key': 'food_and_beverage', 'sort_order': 370},
        {'key': 'food_trucks', 'label': 'Food Trucks', 'parent_key': 'food_and_beverage', 'sort_order': 380},
        {'key': 'grocery_stores', 'label': 'Grocery Stores', 'parent_key': 'food_and_beverage', 'sort_order': 390},
        {'key': 'specialty_foods', 'label': 'Specialty Foods', 'parent_key': 'food_and_beverage', 'sort_order': 400},
        {'key': 'hospitals', 'label': 'Hospitals', 'parent_key': 'healthcare', 'sort_order': 410},
        {'key': 'clinics', 'label': 'Clinics', 'parent_key': 'healthcare', 'sort_order': 420},
        {'key': 'dentistry', 'label': 'Dentistry', 'parent_key': 'healthcare', 'sort_order': 430},
        {'key': 'pharmacy', 'label': 'Pharmacy', 'parent_key': 'healthcare', 'sort_order': 440},
        {'key': 'fitness_centers', 'label': 'Fitness', 'parent_key': 'healthcare', 'sort_order': 450},
        {'key': 'mental_health', 'label': 'Mental Health', 'parent_key': 'healthcare', 'sort_order': 460},
        {'key': 'chiropractic', 'label': 'Chiropractic', 'parent_key': 'healthcare', 'sort_order': 470},
        {'key': 'physical_therapy', 'label': 'Physical Therapy', 'parent_key': 'healthcare', 'sort_order': 480},
        {'key': 'medical_supplies', 'label': 'Medical Supplies', 'parent_key': 'healthcare', 'sort_order': 490},
        {'key': 'home_health_care', 'label': 'Home Health Care', 'parent_key': 'healthcare', 'sort_order': 500},
        {'key': 'schools', 'label': 'Schools', 'parent_key': 'education', 'sort_order': 510},
        {'key': 'universities', 'label': 'Universities', 'parent_key': 'education', 'sort_order': 520},
        {'key': 'tutoring', 'label': 'Tutoring', 'parent_key': 'education', 'sort_order': 530},
        {'key': 'online_learning', 'label': 'Online Learning', 'parent_key': 'education', 'sort_order': 540},
        {'key': 'training', 'label': 'Training', 'parent_key': 'education', 'sort_order': 550},
        {'key': 'courses', 'label': 'Courses', 'parent_key': 'education', 'sort_order': 560},
        {'key': 'daycare', 'label': 'Daycare', 'parent_key': 'education', 'sort_order': 570},
        {'key': 'preschools', 'label': 'Preschools', 'parent_key': 'education', 'sort_order': 580},
        {'key': 'language_schools', 'label': 'Language Schools', 'parent_key': 'education', 'sort_order': 590},
        {'key': 'music_schools', 'label': 'Music Schools', 'parent_key': 'education', 'sort_order': 600},
        {'key': 'residential', 'label': 'Residential', 'parent_key': 'real_estate', 'sort_order': 610},
        {'key': 'commercial', 'label': 'Commercial', 'parent_key': 'real_estate', 'sort_order': 620},
        {'key': 'property_management', 'label': 'Property Management', 'parent_key': 'real_estate', 'sort_order': 630},
        {'key': 'real_estate_agents', 'label': 'Real Estate Agents', 'parent_key': 'real_estate', 'sort_order': 640},
        {'key': 'construction_services', 'label': 'Construction', 'parent_key': 'real_estate', 'sort_order': 650},
        {'key': 'mortgage_brokers', 'label': 'Mortgage Brokers', 'parent_key': 'real_estate', 'sort_order': 660},
        {'key': 'appraisal_services', 'label': 'Appraisal Services', 'parent_key': 'real_estate', 'sort_order': 670},
        {'key': 'property_development', 'label': 'Property Development', 'parent_key': 'real_estate', 'sort_order': 680},
        {'key': 'car_dealerships', 'label': 'Car Dealerships', 'parent_key': 'automotive', 'sort_order': 690},
        {'key': 'auto_repair', 'label': 'Auto Repair', 'parent_key': 'automotive', 'sort_order': 700},
        {'key': 'car_rental', 'label': 'Car Rental', 'parent_key': 'automotive', 'sort_order': 710},
        {'key': 'parts', 'label': 'Parts', 'parent_key': 'automotive', 'sort_order': 720},
        {'key': 'motorcycles', 'label': 'Motorcycles', 'parent_key': 'automotive', 'sort_order': 730},
        {'key': 'towing', 'label': 'Towing', 'parent_key': 'automotive', 'sort_order': 740},
        {'key': 'detailing', 'label': 'Detailing', 'parent_key': 'automotive', 'sort_order': 750},
        {'key': 'car_wash', 'label': 'Car Wash', 'parent_key': 'automotive', 'sort_order': 760},
        {'key': 'tire_shops', 'label': 'Tire Shops', 'parent_key': 'automotive', 'sort_order': 770},
        {'key': 'auto_insurance', 'label': 'Auto Insurance', 'parent_key': 'automotive', 'sort_order': 780},
        {'key': 'hotels', 'label': 'Hotels', 'parent_key': 'hospitality', 'sort_order': 790},
        {'key': 'resorts', 'label': 'Resorts', 'parent_key': 'hospitality', 'sort_order': 800},
        {'key': 'travel_agencies', 'label': 'Travel Agencies', 'parent_key': 'hospitality', 'sort_order': 810},
        {'key': 'tourism', 'label': 'Tourism', 'parent_key': 'hospitality', 'sort_order': 820},
        {'key': 'events', 'label': 'Events', 'parent_key': 'hospitality', 'sort_order': 830},
        {'key': 'bed_breakfast', 'label': 'Bed & Breakfast', 'parent_key': 'hospitality', 'sort_order': 840},
        {'key': 'vacation_rentals', 'label': 'Vacation Rentals', 'parent_key': 'hospitality', 'sort_order': 850},
        {'key': 'cruise_lines', 'label': 'Cruise Lines', 'parent_key': 'hospitality', 'sort_order': 860},
        {'key': 'airbnb_hosts', 'label': 'Airbnb Hosts', 'parent_key': 'hospitality', 'sort_order': 870},
        {'key': 'gyms', 'label': 'Gyms', 'parent_key': 'sports_and_recreation', 'sort_order': 880},
        {'key': 'sports_clubs', 'label': 'Sports Clubs', 'parent_key': 'sports_and_recreation', 'sort_order': 890},
        {'key': 'outdoor_activities', 'label': 'Outdoor Activities', 'parent_key': 'sports_and_recreation', 'sort_order': 900},
        {'key': 'fitness_centers_recreation', 'label': 'Fitness', 'parent_key': 'sports_and_recreation', 'sort_order': 910},
        {'key': 'leisure', 'label': 'Leisure', 'parent_key': 'sports_and_recreation', 'sort_order': 920},
        {'key': 'sports_equipment', 'label': 'Sports Equipment', 'parent_key': 'sports_and_recreation', 'sort_order': 930},
        {'key': 'adventure_sports', 'label': 'Adventure Sports', 'parent_key': 'sports_and_recreation', 'sort_order': 940},
        {'key': 'yoga_studios', 'label': 'Yoga Studios', 'parent_key': 'sports_and_recreation', 'sort_order': 950},
        {'key': 'martial_arts', 'label': 'Martial Arts', 'parent_key': 'sports_and_recreation', 'sort_order': 960},
        {'key': 'dance_studios', 'label': 'Dance Studios', 'parent_key': 'sports_and_recreation', 'sort_order': 970},
        {'key': 'salons', 'label': 'Salons', 'parent_key': 'beauty_and_wellness', 'sort_order': 980},
        {'key': 'spas', 'label': 'Spas', 'parent_key': 'beauty_and_wellness', 'sort_order': 990},
        {'key': 'cosmetics', 'label': 'Cosmetics', 'parent_key': 'beauty_and_wellness', 'sort_order': 1000},
        {'key': 'wellness_centers', 'label': 'Wellness Centers', 'parent_key': 'beauty_and_wellness', 'sort_order': 1010},
        {'key': 'personal_care', 'label': 'Personal Care', 'parent_key': 'beauty_and_wellness', 'sort_order': 1020},
        {'key': 'nail_salons', 'label': 'Nail Salons', 'parent_key': 'beauty_and_wellness', 'sort_order': 1030},
        {'key': 'barber_shops', 'label': 'Barber Shops', 'parent_key': 'beauty_and_wellness', 'sort_order': 1040},
        {'key': 'tattoo_parlors', 'label': 'Tattoo Parlors', 'parent_key': 'beauty_and_wellness', 'sort_order': 1050},
        {'key': 'massage_therapy', 'label': 'Massage Therapy', 'parent_key': 'beauty_and_wellness', 'sort_order': 1060},
        {'key': 'aromatherapy', 'label': 'Aromatherapy', 'parent_key': 'beauty_and_wellness', 'sort_order': 1070},
        {'key': 'home_improvement', 'label': 'Home Improvement', 'parent_key': 'home_and_garden', 'sort_order': 1080},
        {'key': 'gardening', 'label': 'Gardening', 'parent_key': 'home_and_garden', 'sort_order': 1090},
        {'key': 'furniture', 'label': 'Furniture', 'parent_key': 'home_and_garden', 'sort_order': 1100},
        {'key': 'decor', 'label': 'Decor', 'parent_key': 'home_and_garden', 'sort_order': 1110},
        {'key': 'tools', 'label': 'Tools', 'parent_key': 'home_and_garden', 'sort_order': 1120},
        {'key': 'landscaping', 'label': 'Landscaping', 'parent_key': 'home_and_garden', 'sort_order': 1130},
        {'key': 'interior_design', 'label': 'Interior Design', 'parent_key': 'home_and_garden', 'sort_order': 1140},
        {'key': 'home_staging', 'label': 'Home Staging', 'parent_key': 'home_and_garden', 'sort_order': 1150},
        {'key': 'smart_home', 'label': 'Smart Home', 'parent_key': 'home_and_garden', 'sort_order': 1160},
        {'key': 'pest_control', 'label': 'Pest Control', 'parent_key': 'home_and_garden', 'sort_order': 1170},
        {'key': 'accounting', 'label': 'Accounting', 'parent_key': 'professional_services', 'sort_order': 1180},
        {'key': 'marketing', 'label': 'Marketing', 'parent_key': 'professional_services', 'sort_order': 1190},
        {'key': 'advertising', 'label': 'Advertising', 'parent_key': 'professional_services', 'sort_order': 1200},
        {'key': 'consulting', 'label': 'Consulting', 'parent_key': 'professional_services', 'sort_order': 1210},
        {'key': 'legal_services_professional', 'label': 'Legal Services', 'parent_key': 'professional_services', 'sort_order': 1220},
        {'key': 'architecture', 'label': 'Architecture', 'parent_key': 'professional_services', 'sort_order': 1230},
        {'key': 'engineering', 'label': 'Engineering', 'parent_key': 'professional_services', 'sort_order': 1240},
        {'key': 'photography', 'label': 'Photography', 'parent_key': 'professional_services', 'sort_order': 1250},
        {'key': 'graphic_design', 'label': 'Graphic Design', 'parent_key': 'professional_services', 'sort_order': 1260},
        {'key': 'event_planning', 'label': 'Event Planning', 'parent_key': 'professional_services', 'sort_order': 1270},
        {'key': 'movie_theaters', 'label': 'Movie Theaters', 'parent_key': 'entertainment', 'sort_order': 1280},
        {'key': 'music_venues', 'label': 'Music Venues', 'parent_key': 'entertainment', 'sort_order': 1290},
        {'key': 'comedy_clubs', 'label': 'Comedy Clubs', 'parent_key': 'entertainment', 'sort_order': 1300},
        {'key': 'art_galleries', 'label': 'Art Galleries', 'parent_key': 'entertainment', 'sort_order': 1310},
        {'key': 'museums', 'label': 'Museums', 'parent_key': 'entertainment', 'sort_order': 1320},
        {'key': 'theaters', 'label': 'Theaters', 'parent_key': 'entertainment', 'sort_order': 1330},
        {'key': 'concert_halls', 'label': 'Concert Halls', 'parent_key': 'entertainment', 'sort_order': 1340},
        {'key': 'amusement_parks', 'label': 'Amusement Parks', 'parent_key': 'entertainment', 'sort_order': 1350},
        {'key': 'arcades', 'label': 'Arcades', 'parent_key': 'entertainment', 'sort_order': 1360},
        {'key': 'escape_rooms', 'label': 'Escape Rooms', 'parent_key': 'entertainment', 'sort_order': 1370},
        {'key': 'taxi_services', 'label': 'Taxi Services', 'parent_key': 'transportation', 'sort_order': 1380},
        {'key': 'ride_sharing', 'label': 'Ride Sharing', 'parent_key': 'transportation', 'sort_order': 1390},
        {'key': 'delivery_services', 'label': 'Delivery Services', 'parent_key': 'transportation', 'sort_order': 1400},
        {'key': 'logistics', 'label': 'Logistics', 'parent_key': 'transportation', 'sort_order': 1410},
        {'key': 'shipping', 'label': 'Shipping', 'parent_key': 'transportation', 'sort_order': 1420},
        {'key': 'moving_services', 'label': 'Moving Services', 'parent_key': 'transportation', 'sort_order': 1430},
        {'key': 'bus_services', 'label': 'Bus Services', 'parent_key': 'transportation', 'sort_order': 1440},
        {'key': 'rail_services', 'label': 'Rail Services', 'parent_key': 'transportation', 'sort_order': 1450},
        {'key': 'airports', 'label': 'Airports', 'parent_key': 'transportation', 'sort_order': 1460},
        {'key': 'parking', 'label': 'Parking', 'parent_key': 'transportation', 'sort_order': 1470},
        {'key': 'farms', 'label': 'Farms', 'parent_key': 'agriculture', 'sort_order': 1480},
        {'key': 'greenhouses', 'label': 'Greenhouses', 'parent_key': 'agriculture', 'sort_order': 1490},
        {'key': 'nurseries', 'label': 'Nurseries', 'parent_key': 'agriculture', 'sort_order': 1500},
        {'key': 'livestock', 'label': 'Livestock', 'parent_key': 'agriculture', 'sort_order': 1510},
        {'key': 'crop_production', 'label': 'Crop Production', 'parent_key': 'agriculture', 'sort_order': 1520},
        {'key': 'organic_farming', 'label': 'Organic Farming', 'parent_key': 'agriculture', 'sort_order': 1530},
        {'key': 'agricultural_equipment', 'label': 'Agricultural Equipment', 'parent_key': 'agriculture', 'sort_order': 1540},
        {'key': 'seed_suppliers', 'label': 'Seed Suppliers', 'parent_key': 'agriculture', 'sort_order': 1550},
        {'key': 'farmers_markets', 'label': 'Farmers Markets', 'parent_key': 'agriculture', 'sort_order': 1560},
        {'key': 'agricultural_consulting', 'label': 'Agricultural Consulting', 'parent_key': 'agriculture', 'sort_order': 1570},
        {'key': 'banks', 'label': 'Banks', 'parent_key': 'financial_services', 'sort_order': 1580},
        {'key': 'credit_unions', 'label': 'Credit Unions', 'parent_key': 'financial_services', 'sort_order': 1590},
        {'key': 'investment_firms', 'label': 'Investment Firms', 'parent_key': 'financial_services', 'sort_order': 1600},
        {'key': 'insurance', 'label': 'Insurance', 'parent_key': 'financial_services', 'sort_order': 1610},
        {'key': 'mortgage_lenders', 'label': 'Mortgage Lenders', 'parent_key': 'financial_services', 'sort_order': 1620},
        {'key': 'financial_planning', 'label': 'Financial Planning', 'parent_key': 'financial_services', 'sort_order': 1630},
        {'key': 'tax_services', 'label': 'Tax Services', 'parent_key': 'financial_services', 'sort_order': 1640},
        {'key': 'payroll_services', 'label': 'Payroll Services', 'parent_key': 'financial_services', 'sort_order': 1650},
        {'key': 'cryptocurrency', 'label': 'Cryptocurrency', 'parent_key': 'financial_services', 'sort_order': 1660},
        {'key': 'fintech', 'label': 'Fintech', 'parent_key': 'financial_services', 'sort_order': 1670},
        {'key': 'law_firms', 'label': 'Law Firms', 'parent_key': 'legal_services', 'sort_order': 1680},
        {'key': 'notary_services', 'label': 'Notary Services', 'parent_key': 'legal_services', 'sort_order': 1690},
        {'key': 'paralegal_services', 'label': 'Paralegal Services', 'parent_key': 'legal_services', 'sort_order': 1700},
        {'key': 'legal_consulting', 'label': 'Legal Consulting', 'parent_key': 'legal_services', 'sort_order': 1710},
        {'key': 'mediation_services', 'label': 'Mediation Services', 'parent_key': 'legal_services', 'sort_order': 1720},
        {'key': 'court_reporting', 'label': 'Court Reporting', 'parent_key': 'legal_services', 'sort_order': 1730},
        {'key': 'intellectual_property', 'label': 'Intellectual Property', 'parent_key': 'legal_services', 'sort_order': 1740},
        {'key': 'immigration_law', 'label': 'Immigration Law', 'parent_key': 'legal_services', 'sort_order': 1750},
        {'key': 'family_law', 'label': 'Family Law', 'parent_key': 'legal_services', 'sort_order': 1760},
        {'key': 'corporate_law', 'label': 'Corporate Law', 'parent_key': 'legal_services', 'sort_order': 1770},
        {'key': 'general_contractors', 'label': 'General Contractors', 'parent_key': 'construction', 'sort_order': 1780},
        {'key': 'electrical', 'label': 'Electrical', 'parent_key': 'construction', 'sort_order': 1790},
        {'key': 'plumbing', 'label': 'Plumbing', 'parent_key': 'construction', 'sort_order': 1800},
        {'key': 'hvac', 'label': 'HVAC', 'parent_key': 'construction', 'sort_order': 1810},
        {'key': 'roofing', 'label': 'Roofing', 'parent_key': 'construction', 'sort_order': 1820},
        {'key': 'flooring', 'label': 'Flooring', 'parent_key': 'construction', 'sort_order': 1830},
        {'key': 'painting', 'label': 'Painting', 'parent_key': 'construction', 'sort_order': 1840},
        {'key': 'carpentry', 'label': 'Carpentry', 'parent_key': 'construction', 'sort_order': 1850},
        {'key': 'masonry', 'label': 'Masonry', 'parent_key': 'construction', 'sort_order': 1860},
        {'key': 'demolition', 'label': 'Demolition', 'parent_key': 'construction', 'sort_order': 1870},
        {'key': 'newspapers', 'label': 'Newspapers', 'parent_key': 'media_and_communications', 'sort_order': 1880},
        {'key': 'tv_stations', 'label': 'TV Stations', 'parent_key': 'media_and_communications', 'sort_order': 1890},
        {'key': 'radio_stations', 'label': 'Radio Stations', 'parent_key': 'media_and_communications', 'sort_order': 1900},
        {'key': 'podcasting', 'label': 'Podcasting', 'parent_key': 'media_and_communications', 'sort_order': 1910},
        {'key': 'social_media', 'label': 'Social Media', 'parent_key': 'media_and_communications', 'sort_order': 1920},
        {'key': 'public_relations', 'label': 'Public Relations', 'parent_key': 'media_and_communications', 'sort_order': 1930},
        {'key': 'journalism', 'label': 'Journalism', 'parent_key': 'media_and_communications', 'sort_order': 1940},
        {'key': 'film_production', 'label': 'Film Production', 'parent_key': 'media_and_communications', 'sort_order': 1950},
        {'key': 'advertising_agencies', 'label': 'Advertising Agencies', 'parent_key': 'media_and_communications', 'sort_order': 1960},
        {'key': 'publishing', 'label': 'Publishing', 'parent_key': 'media_and_communications', 'sort_order': 1970},
        {'key': 'charities', 'label': 'Charities', 'parent_key': 'non_profit', 'sort_order': 1980},
        {'key': 'foundations', 'label': 'Foundations', 'parent_key': 'non_profit', 'sort_order': 1990},
        {'key': 'ngos', 'label': 'NGOs', 'parent_key': 'non_profit', 'sort_order': 2000},
        {'key': 'community_organizations', 'label': 'Community Organizations', 'parent_key': 'non_profit', 'sort_order': 2010},
        {'key': 'religious_organizations', 'label': 'Religious Organizations', 'parent_key': 'non_profit', 'sort_order': 2020},
        {'key': 'environmental_groups', 'label': 'Environmental Groups', 'parent_key': 'non_profit', 'sort_order': 2030},
        {'key': 'animal_welfare', 'label': 'Animal Welfare', 'parent_key': 'non_profit', 'sort_order': 2040},
        {'key': 'youth_organizations', 'label': 'Youth Organizations', 'parent_key': 'non_profit', 'sort_order': 2050},
        {'key': 'arts_culture', 'label': 'Arts & Culture', 'parent_key': 'non_profit', 'sort_order': 2060},
        {'key': 'education_advocacy', 'label': 'Education Advocacy', 'parent_key': 'non_profit', 'sort_order': 2070},
        {'key': 'municipal_services', 'label': 'Municipal Services', 'parent_key': 'government', 'sort_order': 2080},
        {'key': 'state_agencies', 'label': 'State Agencies', 'parent_key': 'government', 'sort_order': 2090},
        {'key': 'federal_agencies', 'label': 'Federal Agencies', 'parent_key': 'government', 'sort_order': 2100},
        {'key': 'public_safety', 'label': 'Public Safety', 'parent_key': 'government', 'sort_order': 2110},
        {'key': 'utilities', 'label': 'Utilities', 'parent_key': 'government', 'sort_order': 2120},
        {'key': 'transportation_services', 'label': 'Transportation', 'parent_key': 'government', 'sort_order': 2130},
        {'key': 'parks_recreation', 'label': 'Parks & Recreation', 'parent_key': 'government', 'sort_order': 2140},
        {'key': 'libraries', 'label': 'Libraries', 'parent_key': 'government', 'sort_order': 2150},
        {'key': 'courts', 'label': 'Courts', 'parent_key': 'government', 'sort_order': 2160},
        {'key': 'licensing', 'label': 'Licensing', 'parent_key': 'government', 'sort_order': 2170},
    ])

    create_lookup_collection(apps, 'brand_tones', 'Brand Tones', [
        {'key': 'professional', 'label': 'Professional'},
        {'key': 'casual', 'label': 'Casual'},
        {'key': 'funny', 'label': 'Funny'},
        {'key': 'inspirational', 'label': 'Inspirational'},
        {'key': 'urgent', 'label': 'Urgent'},
        {'key': 'friendly', 'label': 'Friendly'},
    ])

    create_lookup_collection(apps, 'genders', 'Genders', [
        {'key': 'all', 'label': 'All'},
        {'key': 'male', 'label': 'Male'},
        {'key': 'female', 'label': 'Female'},
        {'key': 'non_binary', 'label': 'Non-binary'},
        {'key': 'unspecified', 'label': 'Unspecified'},
    ])

    create_lookup_collection(apps, 'months', 'Months', [
        {'key': '01', 'label': 'January', 'value': 'January', 'sort_order': 10},
        {'key': '02', 'label': 'February', 'value': 'February', 'sort_order': 20},
        {'key': '03', 'label': 'March', 'value': 'March', 'sort_order': 30},
        {'key': '04', 'label': 'April', 'value': 'April', 'sort_order': 40},
        {'key': '05', 'label': 'May', 'value': 'May', 'sort_order': 50},
        {'key': '06', 'label': 'June', 'value': 'June', 'sort_order': 60},
        {'key': '07', 'label': 'July', 'value': 'July', 'sort_order': 70},
        {'key': '08', 'label': 'August', 'value': 'August', 'sort_order': 80},
        {'key': '09', 'label': 'September', 'value': 'September', 'sort_order': 90},
        {'key': '10', 'label': 'October', 'value': 'October', 'sort_order': 100},
        {'key': '11', 'label': 'November', 'value': 'November', 'sort_order': 110},
        {'key': '12', 'label': 'December', 'value': 'December', 'sort_order': 120},
    ])

    create_lookup_collection(apps, 'kpi_defs', 'KPI Definitions', [
        {'key': 'impressions', 'label': 'Impressions', 'value': 'impressions', 'sort_order': 10},
        {'key': 'reach', 'label': 'Reach', 'value': 'reach', 'sort_order': 20},
        {'key': 'clicks', 'label': 'Clicks', 'value': 'clicks', 'sort_order': 30},
        {'key': 'likes', 'label': 'Likes', 'value': 'likes', 'sort_order': 40},
        {'key': 'comments', 'label': 'Comments', 'value': 'comments', 'sort_order': 50},
        {'key': 'shares', 'label': 'Shares', 'value': 'shares', 'sort_order': 60},
        {'key': 'video_views', 'label': 'Video Views', 'value': 'video_views', 'sort_order': 70},
        {'key': 'followers', 'label': 'Followers', 'value': 'followers', 'sort_order': 80},
        {'key': 'website_clicks', 'label': 'Website Clicks', 'value': 'website_clicks', 'sort_order': 90},
        {'key': 'phone_calls', 'label': 'Phone Calls', 'value': 'phone_calls', 'sort_order': 100},
    ])


def reverse_func(apps, schema_editor):
    LookupCollection = apps.get_model('social_stats', 'LookupCollection')
    LookupCollection.objects.filter(key__in=[
        'platforms', 'business_types', 'business_categories',
        'business_subcategories', 'brand_tones', 'genders', 'months', 'kpi_defs'
    ]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('social_stats', '0019_lookupcollection_lookupitem'),
    ]

    operations = [
        migrations.RunPython(forward_func, reverse_func),
    ]
