# Generated by Django 4.2.9 on 2026-04-03 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_stats', '0021_remove_platform_lookup_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymetric',
            name='avg_view_duration',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dailymetric',
            name='subscribers_lost',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailymetric',
            name='watch_time_minutes',
            field=models.BigIntegerField(default=0),
        ),
    ]
