# Generated by Django 4.2.9 on 2026-04-03 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_stats', '0022_youtube_watch_time_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymetric',
            name='accounts_engaged',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailymetric',
            name='direction_clicks',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailymetric',
            name='email_contacts',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailymetric',
            name='fb_video_views',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailymetric',
            name='fb_video_watch_time',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailymetric',
            name='followers_lost',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailymetric',
            name='ig_followers_lost',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailymetric',
            name='negative_feedback',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailymetric',
            name='phone_call_clicks',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailymetric',
            name='reactions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='dailymetric',
            name='total_interactions',
            field=models.BigIntegerField(default=0),
        ),
    ]
