# Generated by Django 4.2.9 on 2026-05-07 12:08

from django.db import migrations, models
import django.db.models.deletion
import social_stats.fields


class Migration(migrations.Migration):

    dependencies = [
        ('social_stats', '0034_adswaitlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualCredentialExtras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oauth_client_id', social_stats.fields.EncryptedTextField(blank=True)),
                ('oauth_client_secret', social_stats.fields.EncryptedTextField(blank=True)),
                ('api_key', social_stats.fields.EncryptedTextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name='adswaitlist',
            new_name='social_stat_email_4a9879_idx',
            old_name='social_stat_email_b09e54_idx',
        ),
        migrations.AddField(
            model_name='platformcredential',
            name='auth_method',
            field=models.CharField(choices=[('oauth', 'OAuth'), ('manual_token', 'Manual Token'), ('system_user', 'System User')], default='oauth', max_length=20),
        ),
        migrations.AddField(
            model_name='manualcredentialextras',
            name='credential',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manual_extras', to='social_stats.platformcredential'),
        ),
    ]
