# Generated by Django 4.2.9 on 2026-05-07 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_stats', '0036_unified_control_center'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('viral_post', 'Viral post'), ('engagement_drop', 'Engagement drop'), ('negative_cluster', 'Negative-sentiment cluster'), ('follower_milestone', 'Follower milestone'), ('best_time_window', 'Best-time-to-post window'), ('mention', 'Mention or tag'), ('token_expiring', 'Token expiring soon'), ('publish_failed', 'Publish failed'), ('post_published', 'Post published'), ('approval_pending', 'Post needs approval'), ('inbox_message', 'New inbound message'), ('inbox_review', 'New review')], max_length=40)),
                ('channel', models.CharField(choices=[('in_app', 'In-app'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('browser', 'Browser push')], max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_prefs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', 'event_type', 'channel'],
                'unique_together': {('user', 'event_type', 'channel')},
            },
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, help_text='e.g. composer.publish, inbox.reply, automation.fired', max_length=80)),
                ('object_type', models.CharField(blank=True, help_text='e.g. UnifiedPost, Conversation', max_length=80)),
                ('object_id', models.CharField(blank=True, max_length=80)),
                ('platform', models.CharField(blank=True, max_length=30)),
                ('result', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial')], default='success', max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='social_stats.client')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', '-created_at'], name='social_stat_client__62828c_idx'), models.Index(fields=['client', 'action', '-created_at'], name='social_stat_client__fc9fa9_idx'), models.Index(fields=['actor', '-created_at'], name='social_stat_actor_i_c66d6c_idx')],
            },
        ),
    ]
