# Generated by Django 4.2.9 on 2026-05-07 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_stats', '0038_seed_stage_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Auto-generated from first user message', max_length=200)),
                ('context_type', models.CharField(choices=[('general', 'General'), ('client_specific', 'Client-specific'), ('data_query', 'Data query')], default='general', max_length=20)),
                ('pinned_resources', models.JSONField(blank=True, default=list, help_text='References to specific posts/campaigns/data')),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AIMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=10)),
                ('content', models.TextField()),
                ('attachments', models.JSONField(blank=True, default=list, help_text='[{type, url, name}] image/file refs')),
                ('tool_calls', models.JSONField(blank=True, default=list, help_text='Anthropic tool-use blocks emitted by assistant')),
                ('tool_results', models.JSONField(blank=True, default=list, help_text='Results returned to assistant for follow-up')),
                ('model_used', models.CharField(blank=True, max_length=80)),
                ('tokens_used', models.IntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('feedback', models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIScheduledRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(choices=[('weekly_report', 'Weekly report'), ('monthly_report', 'Monthly report'), ('competitor_check', 'Competitor check'), ('trend_radar', 'Trend radar'), ('crisis_scan', 'Crisis scan'), ('daily_briefing', 'Daily briefing'), ('custom', 'Custom')], max_length=40)),
                ('schedule_rule', models.CharField(blank=True, help_text='iCal RRULE or human-readable cadence', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_status', models.CharField(choices=[('never_run', 'Never run'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='never_run', max_length=20)),
                ('last_result', models.JSONField(blank=True, default=dict)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Per-feature parameters')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AITrainedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('post', 'Post'), ('article', 'Article'), ('document', 'Document'), ('website', 'Website'), ('faq', 'FAQ'), ('brand', 'Brand guideline')], max_length=20)),
                ('source_id', models.CharField(blank=True, help_text='External id (post id, doc id) for de-dup', max_length=120)),
                ('content', models.TextField()),
                ('embedding', models.JSONField(blank=True, default=list, help_text='Vector — empty until RAG is enabled')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('indexed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(help_text='caption | reply_suggest | chat | sentiment | …', max_length=60)),
                ('model', models.CharField(max_length=80)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('total_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('request_id', models.CharField(blank=True, help_text='Anthropic request id', max_length=120)),
                ('prompt_hash', models.CharField(blank=True, help_text='For dedup analytics', max_length=64)),
                ('cached', models.BooleanField(default=False)),
                ('request_payload', models.JSONField(blank=True, default=dict, help_text='Sanitised request preview')),
                ('response_summary', models.TextField(blank=True, help_text='First ~200 chars of response')),
                ('duration_ms', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('rate_limited', 'Rate limited'), ('budget_capped', 'Budget capped')], default='success', max_length=20)),
                ('error_message', models.CharField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='aiinsight',
            options={'ordering': ['-generated_at']},
        ),
        migrations.AlterUniqueTogether(
            name='aiinsight',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='aiinsight',
            name='acted_upon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aiinsight',
            name='action_recommended',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aiinsight',
            name='confidence_score',
            field=models.FloatField(default=0.0, help_text='0.0-1.0 — how certain Claude is about this insight'),
        ),
        migrations.AddField(
            model_name='aiinsight',
            name='data_sources',
            field=models.JSONField(blank=True, default=list, help_text='Brief description of what was analysed'),
        ),
        migrations.AddField(
            model_name='aiinsight',
            name='dismissed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aiinsight',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiinsight',
            name='insight_type',
            field=models.CharField(blank=True, help_text='engagement_trend, competitor_alert, best_time_shift, etc.', max_length=60),
        ),
        migrations.AddField(
            model_name='aiinsight',
            name='severity',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='aiinsight',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='brandvoiceprofile',
            name='emoji_usage',
            field=models.CharField(blank=True, choices=[('heavy', 'Heavy'), ('moderate', 'Moderate'), ('minimal', 'Minimal'), ('none', 'None')], default='moderate', max_length=10),
        ),
        migrations.AddField(
            model_name='brandvoiceprofile',
            name='hashtag_style',
            field=models.CharField(blank=True, help_text='e.g. "minimal", "grouped-at-end", "inline"', max_length=30),
        ),
        migrations.AddField(
            model_name='brandvoiceprofile',
            name='preferred_words',
            field=models.JSONField(blank=True, default=list, help_text='Brand vocabulary to favour'),
        ),
        migrations.AddField(
            model_name='brandvoiceprofile',
            name='prohibited_topics',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='brandvoiceprofile',
            name='target_audience',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='brandvoiceprofile',
            name='training_error',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='brandvoiceprofile',
            name='training_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('training', 'Training'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='aiinsight',
            name='month',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aiinsight',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='brandvoiceprofile',
            name='forbidden_words',
            field=models.JSONField(blank=True, default=list, help_text='Words/phrases to avoid'),
        ),
        migrations.AddIndex(
            model_name='aiinsight',
            index=models.Index(fields=['client', '-generated_at'], name='social_stat_client__988713_idx'),
        ),
        migrations.AddIndex(
            model_name='aiinsight',
            index=models.Index(fields=['client', 'dismissed', '-generated_at'], name='social_stat_client__ff3bae_idx'),
        ),
        migrations.AddIndex(
            model_name='aiinsight',
            index=models.Index(fields=['insight_type'], name='social_stat_insight_a7ab60_idx'),
        ),
        migrations.AddField(
            model_name='aiusagelog',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage_logs', to='social_stats.client'),
        ),
        migrations.AddField(
            model_name='aiusagelog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aitrainedasset',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_trained_assets', to='social_stats.client'),
        ),
        migrations.AddField(
            model_name='aischeduledrun',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_scheduled_runs', to='social_stats.client'),
        ),
        migrations.AddField(
            model_name='aimessage',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='social_stats.aiconversation'),
        ),
        migrations.AddField(
            model_name='aiconversation',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to='social_stats.client'),
        ),
        migrations.AddField(
            model_name='aiconversation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='aiusagelog',
            index=models.Index(fields=['client', '-created_at'], name='social_stat_client__f6441a_idx'),
        ),
        migrations.AddIndex(
            model_name='aiusagelog',
            index=models.Index(fields=['user', '-created_at'], name='social_stat_user_id_349acf_idx'),
        ),
        migrations.AddIndex(
            model_name='aiusagelog',
            index=models.Index(fields=['feature', '-created_at'], name='social_stat_feature_133b9d_idx'),
        ),
        migrations.AddIndex(
            model_name='aiusagelog',
            index=models.Index(fields=['prompt_hash'], name='social_stat_prompt__cdbb9e_idx'),
        ),
        migrations.AddIndex(
            model_name='aitrainedasset',
            index=models.Index(fields=['client', 'asset_type', '-updated_at'], name='social_stat_client__c4ae6a_idx'),
        ),
        migrations.AddIndex(
            model_name='aitrainedasset',
            index=models.Index(fields=['client', 'source_id'], name='social_stat_client__6723fe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='aischeduledrun',
            unique_together={('client', 'feature')},
        ),
        migrations.AddIndex(
            model_name='aimessage',
            index=models.Index(fields=['conversation', 'created_at'], name='social_stat_convers_8a2339_idx'),
        ),
        migrations.AddIndex(
            model_name='aiconversation',
            index=models.Index(fields=['user', 'archived', '-updated_at'], name='social_stat_user_id_b8e0f9_idx'),
        ),
        migrations.AddIndex(
            model_name='aiconversation',
            index=models.Index(fields=['client', '-updated_at'], name='social_stat_client__230574_idx'),
        ),
    ]
