# Generated by Django 4.2.9 on 2026-05-08 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_stats', '0040_marketplace_foundation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('invitation_received', 'Invitation Received'), ('invitation_accepted', 'Invitation Accepted'), ('invitation_rejected', 'Invitation Rejected'), ('invitation_cancelled', 'Invitation Cancelled'), ('manage_request_received', 'Manage Request Received'), ('manage_request_accepted', 'Manage Request Accepted'), ('manage_request_declined', 'Manage Request Declined'), ('manage_request_cancelled', 'Manage Request Cancelled'), ('system', 'System')], default='system', max_length=30),
        ),
    ]
