# Generated by Django 4.2.9 on 2026-05-08 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_stats', '0042_billing'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='agency',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='social_stats.agency'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='client',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='social_stats.client'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('client__isnull', False), ('agency__isnull', True)), models.Q(('client__isnull', True), ('agency__isnull', False)), _connector='OR'), name='subscription_exactly_one_subject'),
        ),
    ]
