# Generated by Django 4.2.9 on 2026-05-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_stats', '0043_agency_billing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationpreference',
            name='event_type',
            field=models.CharField(choices=[('viral_post', 'Viral post'), ('engagement_drop', 'Engagement drop'), ('negative_cluster', 'Negative-sentiment cluster'), ('follower_milestone', 'Follower milestone'), ('best_time_window', 'Best-time-to-post window'), ('mention', 'Mention or tag'), ('token_expiring', 'Token expiring soon'), ('publish_failed', 'Publish failed'), ('post_published', 'Post published'), ('approval_pending', 'Post needs approval'), ('inbox_message', 'New inbound message'), ('inbox_review', 'New review'), ('manage_request_received', 'Agency wants to manage your account'), ('agency_invite_received', 'Client invited your agency'), ('relation_terminated', 'Agency relationship ended'), ('approval_requested', 'Action needs your approval'), ('approval_decided', 'Your approval request was decided'), ('new_review_received', 'New review left for your agency'), ('review_response', 'Agency replied to your review'), ('marketplace_inquiry', 'Marketplace inquiry')], max_length=40),
        ),
    ]
