# Generated by Django 4.2.9 on 2026-05-08 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_stats', '0044_marketplace_notif_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('evidence_urls', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under review'), ('resolved', 'Resolved'), ('rejected', 'Rejected'), ('escalated', 'Escalated')], default='open', max_length=20)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('resolution', models.TextField(blank=True)),
                ('action_taken', models.CharField(blank=True, choices=[('paused', 'Paused relation'), ('terminated', 'Terminated relation'), ('warned', 'Warned agency'), ('dismissed', 'Dismissed'), ('escalated', 'Escalated to legal')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_disputes', to=settings.AUTH_USER_MODEL)),
                ('filer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filed_disputes', to=settings.AUTH_USER_MODEL)),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='social_stats.agencyclientrelation')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='social_stat_status_54e544_idx'), models.Index(fields=['relation'], name='social_stat_relatio_1e5ddd_idx'), models.Index(fields=['filer'], name='social_stat_filer_i_e963e2_idx')],
            },
        ),
    ]
