# Generated by Django 4.2.9 on 2026-05-08 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_stats', '0045_disputes'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_via', models.CharField(max_length=50)),
                ('trigger_metadata', models.JSONField(blank=True, default=dict)),
                ('current_node_id', models.CharField(blank=True, max_length=50)),
                ('variables', models.JSONField(blank=True, default=dict)),
                ('path_history', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed Successfully'), ('abandoned', 'User Stopped Replying'), ('handed_off', 'Handed Off to Human'), ('failed', 'Bot Errored'), ('exited', 'User Exited Flow')], default='active', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('lead_captured', models.BooleanField(default=False)),
                ('handed_off_at', models.DateTimeField(blank=True, null=True)),
                ('ai_takeover_active', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_conversations', to='social_stats.client')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_conversations', to='social_stats.whatsappcontact')),
            ],
        ),
        migrations.CreateModel(
            name='BotFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('trigger_type', models.CharField(choices=[('ctwa_ad', 'Click-to-WhatsApp Ad'), ('keyword', 'Keyword in Message'), ('first_message', 'First Message Ever'), ('button_reply', 'Button/List Reply'), ('referral_link', 'WhatsApp Link Referral'), ('manual', 'Manually Triggered')], default='ctwa_ad', max_length=30)),
                ('trigger_config', models.JSONField(blank=True, default=dict)),
                ('nodes', models.JSONField(blank=True, default=list)),
                ('edges', models.JSONField(blank=True, default=list)),
                ('starting_node_id', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('is_template', models.BooleanField(default=False)),
                ('version', models.IntegerField(default=1)),
                ('published_version', models.IntegerField(blank=True, null=True)),
                ('last_published_at', models.DateTimeField(blank=True, null=True)),
                ('total_triggered', models.IntegerField(default=0)),
                ('total_completed', models.IntegerField(default=0)),
                ('total_leads_captured', models.IntegerField(default=0)),
                ('business_hours_only', models.BooleanField(default=False)),
                ('business_hours', models.JSONField(blank=True, default=dict)),
                ('out_of_hours_message', models.TextField(blank=True)),
                ('ai_fallback_enabled', models.BooleanField(default=False)),
                ('ai_fallback_persona', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_flows', to='social_stats.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('interest', models.CharField(blank=True, max_length=200)),
                ('budget', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('custom_fields', models.JSONField(blank=True, default=dict)),
                ('source_channel', models.CharField(default='whatsapp', max_length=50)),
                ('source_ad_id', models.CharField(blank=True, max_length=100)),
                ('source_ad_name', models.CharField(blank=True, max_length=200)),
                ('source_campaign_id', models.CharField(blank=True, max_length=100)),
                ('source_campaign_name', models.CharField(blank=True, max_length=200)),
                ('source_adset_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('converted', 'Converted'), ('lost', 'Lost'), ('spam', 'Spam')], default='new', max_length=20)),
                ('quality_score', models.IntegerField(default=50)),
                ('quality_reason', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('conversion_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='social_stats.client')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='social_stats.whatsappcontact')),
                ('source_conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='social_stats.botconversation')),
                ('source_flow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='social_stats.botflow')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CTWACampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ad_account_id', models.CharField(max_length=100)),
                ('campaign_id', models.CharField(max_length=100)),
                ('campaign_name', models.CharField(blank=True, max_length=200)),
                ('adset_ids', models.JSONField(blank=True, default=list)),
                ('ad_ids', models.JSONField(blank=True, default=list)),
                ('pre_filled_message', models.CharField(default='Hello', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('total_clicks', models.IntegerField(default=0)),
                ('total_conversations', models.IntegerField(default=0)),
                ('total_leads', models.IntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ctwa_campaigns', to='social_stats.client')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ctwa_campaigns', to='social_stats.botflow')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BotFlowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('industry', models.CharField(choices=[('real_estate', 'Real Estate'), ('healthcare', 'Healthcare'), ('restaurant', 'Restaurant'), ('fitness', 'Fitness / Gym'), ('education', 'Education'), ('ecommerce', 'E-commerce'), ('professional', 'Professional Services'), ('general', 'General')], default='general', max_length=50)),
                ('use_case', models.CharField(choices=[('lead_capture', 'Lead Capture'), ('appointment_booking', 'Appointment Booking'), ('product_inquiry', 'Product Inquiry'), ('feedback_collection', 'Feedback Collection'), ('support', 'Customer Support Triage'), ('lead_magnet', 'Lead Magnet Delivery')], default='lead_capture', max_length=50)),
                ('cover_image', models.URLField(blank=True)),
                ('nodes', models.JSONField(blank=True, default=list)),
                ('edges', models.JSONField(blank=True, default=list)),
                ('starting_node_id', models.CharField(blank=True, max_length=50)),
                ('is_featured', models.BooleanField(default=False)),
                ('use_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_featured', '-use_count', '-created_at'],
                'indexes': [models.Index(fields=['industry', 'use_case'], name='social_stat_industr_05efdf_idx'), models.Index(fields=['is_featured', '-use_count'], name='social_stat_is_feat_8def9b_idx')],
            },
        ),
        migrations.CreateModel(
            name='BotConversationStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=50)),
                ('node_type', models.CharField(max_length=30)),
                ('direction', models.CharField(choices=[('bot_to_user', 'Bot → User'), ('user_to_bot', 'User → Bot'), ('system', 'System')], max_length=12)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='social_stats.botconversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='botconversation',
            name='flow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='social_stats.botflow'),
        ),
        migrations.AddField(
            model_name='botconversation',
            name='handed_off_to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='botconversation',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='social_stats.lead'),
        ),
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('note', 'Note'), ('call', 'Call Logged'), ('email', 'Email Sent'), ('whatsapp', 'WhatsApp Message'), ('status_change', 'Status Change'), ('assignment', 'Assignment'), ('tag', 'Tag Added')], max_length=30)),
                ('content', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='social_stats.lead')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['lead', '-created_at'], name='social_stat_lead_id_5b55c5_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['client', '-created_at'], name='social_stat_client__2387b6_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['client', 'status'], name='social_stat_client__dd1ce7_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['source_campaign_id'], name='social_stat_source__2f8fd3_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['assigned_to', 'status'], name='social_stat_assigne_2d9051_idx'),
        ),
        migrations.AddIndex(
            model_name='ctwacampaign',
            index=models.Index(fields=['client', 'is_active'], name='social_stat_client__6543c2_idx'),
        ),
        migrations.AddIndex(
            model_name='ctwacampaign',
            index=models.Index(fields=['campaign_id'], name='social_stat_campaig_4b8b3f_idx'),
        ),
        migrations.AddIndex(
            model_name='botflow',
            index=models.Index(fields=['client', 'is_active'], name='social_stat_client__52a026_idx'),
        ),
        migrations.AddIndex(
            model_name='botflow',
            index=models.Index(fields=['client', 'trigger_type', 'is_active'], name='social_stat_client__c69005_idx'),
        ),
        migrations.AddIndex(
            model_name='botflow',
            index=models.Index(fields=['is_template'], name='social_stat_is_temp_d1c161_idx'),
        ),
        migrations.AddIndex(
            model_name='botconversationstep',
            index=models.Index(fields=['conversation', 'created_at'], name='social_stat_convers_dd1334_idx'),
        ),
        migrations.AddIndex(
            model_name='botconversationstep',
            index=models.Index(fields=['node_type'], name='social_stat_node_ty_90ee39_idx'),
        ),
        migrations.AddIndex(
            model_name='botconversation',
            index=models.Index(fields=['client', '-started_at'], name='social_stat_client__189113_idx'),
        ),
        migrations.AddIndex(
            model_name='botconversation',
            index=models.Index(fields=['flow', 'status'], name='social_stat_flow_id_c88f03_idx'),
        ),
        migrations.AddIndex(
            model_name='botconversation',
            index=models.Index(fields=['contact', '-last_activity_at'], name='social_stat_contact_a7daba_idx'),
        ),
        migrations.AddIndex(
            model_name='botconversation',
            index=models.Index(fields=['client', 'contact', 'status'], name='social_stat_client__bc2b40_idx'),
        ),
    ]
