# Generated by Django 4.2.9 on 2026-05-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_stats', '0047_seed_bot_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='meta_capi_test_code',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='client',
            name='meta_pixel_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='lead',
            name='capi_pushed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
