# Generated by Django 4.2.9 on 2026-05-08 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_stats', '0049_bot_safety_controls'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_jti', models.CharField(db_index=True, max_length=64, unique=True)),
                ('parent_jti', models.CharField(blank=True, db_index=True, max_length=64)),
                ('user_agent', models.TextField(blank=True)),
                ('ua_browser', models.CharField(blank=True, max_length=60)),
                ('ua_os', models.CharField(blank=True, max_length=60)),
                ('ua_device', models.CharField(blank=True, max_length=60)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('location_country', models.CharField(blank=True, max_length=2)),
                ('location_city', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoke_reason', models.CharField(blank=True, max_length=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_used_at'],
                'indexes': [models.Index(fields=['user', '-last_used_at'], name='social_stat_user_id_e02dbe_idx'), models.Index(fields=['user', 'revoked_at'], name='social_stat_user_id_fc61d6_idx')],
            },
        ),
    ]
