# Generated by Django 4.2.9 on 2026-05-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_stats', '0052_apikey'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(db_index=True, max_length=30)),
                ('event_id', models.CharField(db_index=True, max_length=200)),
                ('payload_hash', models.CharField(max_length=64)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['provider', 'event_id'], name='social_stat_provide_1744b8_idx'), models.Index(fields=['received_at'], name='social_stat_receive_6bb251_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='webhookevent',
            constraint=models.UniqueConstraint(fields=('provider', 'event_id'), name='webhook_event_unique_per_provider'),
        ),
    ]
