# Generated by Django 4.2.9 on 2026-05-08 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_stats', '0053_webhookevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('event_type', models.CharField(db_index=True, max_length=60)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=10)),
                ('actor_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('actor_user_agent', models.TextField(blank=True)),
                ('actor_country', models.CharField(blank=True, max_length=2)),
                ('target_object_type', models.CharField(blank=True, max_length=60)),
                ('target_object_id', models.CharField(blank=True, max_length=64)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('success', models.BooleanField(default=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_audit_actor', to=settings.AUTH_USER_MODEL)),
                ('target_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_audit_targeted', to='social_stats.client')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='social_stat_timesta_b3e78f_idx'), models.Index(fields=['actor_user', '-timestamp'], name='social_stat_actor_u_9396fd_idx'), models.Index(fields=['target_client', '-timestamp'], name='social_stat_target__ece774_idx'), models.Index(fields=['event_type', '-timestamp'], name='social_stat_event_t_23191d_idx'), models.Index(fields=['severity', '-timestamp'], name='social_stat_severit_cb66af_idx')],
            },
        ),
    ]
