# Generated by Django 4.2.9 on 2026-05-08 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_stats', '0054_securityauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_processing_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='UserConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_type', models.CharField(choices=[('marketing_emails', 'Marketing emails'), ('product_emails', 'Product update emails'), ('cookies_analytics', 'Analytics cookies'), ('cookies_marketing', 'Marketing cookies'), ('ai_processing_optout', 'AI processing — opt out'), ('whatsapp_marketing', 'WhatsApp marketing messages'), ('data_processing', 'Core service data processing')], db_index=True, max_length=40)),
                ('given', models.BooleanField()),
                ('given_at', models.DateTimeField(auto_now_add=True)),
                ('given_via', models.CharField(blank=True, max_length=40)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('text_version', models.CharField(blank=True, max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-given_at'],
                'indexes': [models.Index(fields=['user', 'consent_type', '-given_at'], name='social_stat_user_id_234554_idx')],
            },
        ),
        migrations.CreateModel(
            name='DataExportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Download Expired')], default='queued', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('archive_path', models.CharField(blank=True, max_length=500)),
                ('archive_size_bytes', models.BigIntegerField(default=0)),
                ('download_token', models.UUIDField(blank=True, db_index=True, null=True)),
                ('download_expires_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_export_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['user', '-requested_at'], name='social_stat_user_id_83f169_idx'), models.Index(fields=['status'], name='social_stat_status_3a69c2_idx')],
            },
        ),
        migrations.CreateModel(
            name='AccountDeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email_at_request', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('queued', 'Queued (in grace period)'), ('cancelled', 'Cancelled by user'), ('processing', 'Processing'), ('completed', 'Completed (anonymised)'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('grace_until', models.DateTimeField(db_index=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('anonymised_user_id_hash', models.CharField(blank=True, max_length=64)),
                ('error_message', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deletion_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['status', 'grace_until'], name='social_stat_status_ebabe7_idx')],
            },
        ),
    ]
