# Generated by Django 4.2.9 on 2026-05-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_stats', '0055_client_is_processing_paused_userconsent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappcontact',
            name='opt_in_evidence',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='whatsappcontact',
            name='opt_out_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whatsappcontact',
            name='opt_out_keyword',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
