# Generated by Django 4.2.9 on 2026-05-08 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_stats', '0056_whatsappcontact_opt_in_evidence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformDataDeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('meta', 'Meta (Facebook / Instagram)'), ('google', 'Google')], db_index=True, max_length=20)),
                ('kind', models.CharField(choices=[('data_deletion', 'Data deletion request'), ('deauthorize', 'Deauthorization (app removed)')], default='data_deletion', max_length=20)),
                ('external_user_id', models.CharField(db_index=True, max_length=80)),
                ('confirmation_code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('matched_credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deletion_requests', to='social_stats.platformcredential')),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['provider', 'status'], name='social_stat_provide_f122e8_idx'), models.Index(fields=['provider', 'external_user_id'], name='social_stat_provide_86cc06_idx')],
            },
        ),
    ]
