# Generated by Django 4.2.9 on 2026-05-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_stats', '0057_platformdatadeletionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformcredential',
            name='platform_user_id',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
    ]
