# Generated by Django 4.2.9 on 2026-05-09 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


def _backfill_step_client(apps, schema_editor):
    """Copy `BotConversation.client_id` onto each existing BotConversationStep
    row so the new denormalised FK is populated for old data.

    Iterates in chunks of 1000 so we don't load the whole table into memory on
    large prod tables. Idempotent: only touches rows where client is still NULL.
    """
    BotConversationStep = apps.get_model('social_stats', 'BotConversationStep')
    BotConversation     = apps.get_model('social_stats', 'BotConversation')

    # Build a {conversation_id: client_id} map once, then bulk-update in chunks.
    # Far cheaper than one UPDATE per row when there are millions of steps.
    conv_to_client = dict(BotConversation.objects.values_list('id', 'client_id'))

    chunk = []
    qs = BotConversationStep.objects.filter(client__isnull=True).only('id', 'conversation_id')
    for step in qs.iterator(chunk_size=1000):
        client_id = conv_to_client.get(step.conversation_id)
        if not client_id:
            continue
        step.client_id = client_id
        chunk.append(step)
        if len(chunk) >= 1000:
            BotConversationStep.objects.bulk_update(chunk, ['client_id'])
            chunk = []
    if chunk:
        BotConversationStep.objects.bulk_update(chunk, ['client_id'])


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_stats', '0058_platformcredential_platform_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('actor_type', models.CharField(choices=[('user', 'User'), ('agency', 'Agency'), ('system', 'System'), ('ai', 'AI')], default='system', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('correlation_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('processed_by_handlers', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='botconversationstep',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bot_conversation_steps', to='social_stats.client'),
        ),
        migrations.RunPython(
            code=_backfill_step_client,
            reverse_code=migrations.RunPython.noop,
            elidable=True,
        ),
        migrations.AddField(
            model_name='conversation',
            name='last_outbound_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='linked_flow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbox_conversations', to='social_stats.botflow'),
        ),
        migrations.AddField(
            model_name='lead',
            name='source_post',
            field=models.ForeignKey(blank=True, help_text='Set when a Lead originated from a reply/comment on an organic post.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='social_stats.unifiedpost'),
        ),
        migrations.AddField(
            model_name='lead',
            name='source_whatsapp_campaign',
            field=models.ForeignKey(blank=True, help_text='Set when a Lead came in through a WhatsApp broadcast campaign.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='social_stats.whatsappcampaign'),
        ),
        migrations.AddField(
            model_name='message',
            name='linked_bot_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='social_stats.botconversationstep'),
        ),
        migrations.AddField(
            model_name='notification',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='social_stats.client'),
        ),
        migrations.AddIndex(
            model_name='botconversationstep',
            index=models.Index(fields=['client', '-created_at'], name='social_stat_client__1df5e9_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'client', '-created_at'], name='social_stat_user_id_8d5553_idx'),
        ),
        migrations.AddField(
            model_name='eventlog',
            name='actor_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventlog',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_log', to='social_stats.client'),
        ),
        migrations.AddIndex(
            model_name='eventlog',
            index=models.Index(fields=['client', 'event_type', '-created_at'], name='social_stat_client__7e7ddc_idx'),
        ),
        migrations.AddIndex(
            model_name='eventlog',
            index=models.Index(fields=['correlation_id'], name='social_stat_correla_c5258f_idx'),
        ),
    ]
